In [2]:
import pandas as pd
import numpy as np
import datetime as dt

In [11]:

april2018 = pd.read_csv('April_2018.csv')
april2019 = pd.read_csv('April_2019.csv')
april2020 = pd.read_csv('April_2020.csv')

In [12]:
april2018

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,329,37:37.0,43:06.6,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29284,Subscriber,1981,1
1,118,37:30.1,39:28.4,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29465,Subscriber,1966,1
2,76,26:17.9,27:34.7,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29681,Subscriber,1975,1
3,578,10:36.2,20:14.9,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,31695,Subscriber,1970,1
4,485,21:47.9,29:53.3,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31802,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17104,239,24:17.9,28:17.8,3640,Journal Square,40.733670,-74.062500,3194,McGinley Square,40.725340,-74.067622,29616,Subscriber,1990,1
17105,364,45:26.5,51:31.5,3640,Journal Square,40.733670,-74.062500,3212,Christ Hospital,40.734786,-74.050444,26228,Subscriber,1986,2
17106,336,38:32.7,44:09.1,3640,Journal Square,40.733670,-74.062500,3207,Oakland Ave,40.737604,-74.052478,31954,Subscriber,1971,1
17107,194,08:09.5,11:23.7,3640,Journal Square,40.733670,-74.062500,3201,Dey St,40.737711,-74.066921,29491,Subscriber,1963,1
17108,290,54:45.1,59:35.4,3640,Journal Square,40.733670,-74.062500,3207,Oakland Ave,40.737604,-74.052478,31681,Subscriber,1989,1

In [15]:
#Add the Year and month columns to 2018
april2018 = april2018.assign(year = '2018')
april2018 = april2018.assign(month = 'April')
april2018

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,year,month
0,329,37:37.0,43:06.6,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29284,Subscriber,1981,1,2018,April
1,118,37:30.1,39:28.4,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29465,Subscriber,1966,1,2018,April
2,76,26:17.9,27:34.7,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29681,Subscriber,1975,1,2018,April
3,578,10:36.2,20:14.9,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,31695,Subscriber,1970,1,2018,April
4,485,21:47.9,29:53.3,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31802,Subscriber,1979,1,2018,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17104,239,24:17.9,28:17.8,3640,Journal Square,40.733670,-74.062500,3194,McGinley Square,40.725340,-74.067622,29616,Subscriber,1990,1,2018,April
17105,364,45:26.5,51:31.5,3640,Journal Square,40.733670,-74.062500,3212,Christ Hospital,40.734786,-74.050444,26228,Subscriber,1986,2,2018,April
17106,336,38:32.7,44:09.1,3640,Journal Square,40.733670,-74.062500,3207,Oakland Ave,40.737604,-74.052478,31954,Subscriber,1971,1,2018,April
17107,194,08:09.5,11:23.7,3640,Journal Square,40.733670,-74.062500,3201,Dey St,40.737711,-74.066921,29491,Subscriber,1963,1,2018,April
17108,290,54:45.1,59:35.4,3640,Journal Square,40.733670,-74.062500,3207,Oakland Ave,40.737604,-74.052478,31681,Subscriber,1989,1,2018,April

In [16]:
#Add the Year and month columns to 2019
april2019 = april2019.assign(year = '2019')
april2019 = april2019.assign(month = 'April')
april2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,year,month
0,306,47:08.2,52:14.7,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26272,Subscriber,1989,1,2019,April
1,123,30:53.0,32:56.8,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26192,Subscriber,1966,1,2019,April
2,328,18:30.4,23:59.1,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,26226,Subscriber,1971,2,2019,April
3,95,04:47.2,06:22.8,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26204,Subscriber,1985,1,2019,April
4,169,51:29.4,54:19.2,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29449,Subscriber,1971,1,2019,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23601,916,38:36.2,53:53.0,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29277,Subscriber,1988,1,2019,April
23602,661,29:18.8,40:20.3,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26235,Subscriber,1983,2,2019,April
23603,577,43:09.2,52:46.7,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730897,-74.063913,29596,Subscriber,1988,1,2019,April
23604,585,33:21.5,43:06.8,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730897,-74.063913,26192,Subscriber,1988,1,2019,April
23605,914,59:32.4,14:46.8,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29634,Subscriber,1993,2,2019,April

In [17]:
#Add the Year and month columns to 2020
april2020 = april2020.assign(year = '2020')
april2020 = april2020.assign(month = 'April')
april2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,year,month
0,389,14:07.0,20:36.1,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1,2020,April
1,242,48:06.4,52:09.0,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1,2020,April
2,124,08:46.5,10:51.3,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0,2020,April
3,104,22:35.5,24:20.2,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1,2020,April
4,228,39:20.3,43:09.1,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1,2020,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17714,296,50:39.0,55:35.6,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1,2020,April
17715,147,09:16.0,11:43.5,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1,2020,April
17716,364,17:02.0,23:06.8,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1,2020,April
17717,1217,36:10.6,56:27.8,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1,2020,April
17718,846,37:21.2,51:28.1,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1,2020,April

In [18]:
#Combine all into one spreadsheet

combined_data = april2018.append([april2019, april2020], ignore_index = True)

combined_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,year,month
0,329,37:37.0,43:06.6,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29284,Subscriber,1981,1,2018,April
1,118,37:30.1,39:28.4,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29465,Subscriber,1966,1,2018,April
2,76,26:17.9,27:34.7,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29681,Subscriber,1975,1,2018,April
3,578,10:36.2,20:14.9,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,31695,Subscriber,1970,1,2018,April
4,485,21:47.9,29:53.3,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31802,Subscriber,1979,1,2018,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58429,296,50:39.0,55:35.6,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1,2020,April
58430,147,09:16.0,11:43.5,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1,2020,April
58431,364,17:02.0,23:06.8,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1,2020,April
58432,1217,36:10.6,56:27.8,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1,2020,April
58433,846,37:21.2,51:28.1,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1,2020,April